name: Deploy apps to Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-deploy-pds-web:
    name: Deploy Pds.Web
    runs-on: ubuntu-latest
    environment: pds_dev

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Pds/Pds.Web
      
    - name: Build Pds.Web
      run: dotnet build --no-restore --configuration Debug
      working-directory: Pds/Pds.Web
      
    - name: Publish Pds.Web
      run: dotnet publish -c Debug -o pds_web
      working-directory: Pds/Pds.Web
      
    - name: 'Deploy Pds.Web to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.PDS_WEB_AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PDS_WEB_DEV_AZURE_PUBLISH_PROFILE }}
        package: Pds/Pds.Web/pds_web/  

