name: Build Pds.Web

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.2
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Pds/Pds.Web
    - name: Build
      run: dotnet build --no-restore
      working-directory: Pds/Pds.Web
