name: Build & deploy Pds.Web

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-deploy-pds-web:
    name: Build & Deploy Pds.Web
    runs-on: ubuntu-latest
    environment: pds_prod

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Pds/Pds.Web
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: Pds/Pds.Web
      
    - name: Publish
      run: dotnet publish -c Release -o pds_web
      working-directory: Pds/Pds.Web
      
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.PDS_WEB_AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PDS_WEB_AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: pds_web  

