name: Build & deploy Pds.Web

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-app:
    name: Build Pds.Web
    runs-on: ubuntu-latest
    environment: pds_prod

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Pds/Pds.Web
    - name: Build
      run: dotnet build --no-restore
      working-directory: Pds/Pds.Web
      
  deploy-app:
    name: Deploy Pds.Web
    runs-on: ubuntu-latest
    environment: pds_prod
    
    steps:
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.PDS_WEB_AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PDS_WEB_AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  

